name: Bug report
description: Create a report to help us improve
labels: ['bug']
assignees: ['vaibhav-OP']
body:
  - type: textarea
    attributes:
      label: To Reproduce
      description: 'Steps to reproduce the behavior:'
